replicaCount: 2

image:
  repository: ghcr.io/pthanureddy/backstage-ai-workflow-capabilities
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7007

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
